name: autocoder
run-name: Auto update repo
on: [push]
jobs:
  python_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.PAT }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - run: pip install -r requirements.txt
      - run: mkdir 01_r-markdown
      - run: touch 01_r-markdown/test.txt
      - run: mkdir 02_python
      - run: touch 02_python/test.txt
      - run: python testscript.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update all files